name: ampban
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.6.2.post1=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310ha75aee5_5
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - babel=2.16.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.2.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py310hf71b8c6_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.9=py310hf71b8c6_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.30.0=pyh707e725_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.2=pyhff2d567_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - json5=0.10.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310hff52083_1
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.6=pyhff2d567_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - krb5=1.21.3=h143b758_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.47.0=hadc24fc_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=3.0.2=py310h89163eb_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - nbclient=0.10.1=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook=7.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - openssl=3.4.0=hb9d3cd8_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py310h06a4308_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.1.0=py310ha75aee5_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.18.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.15=h4a871b0_2_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_0
  - python-fastjsonschema=2.21.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.10=5_cp310
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310ha75aee5_1
  - pyzmq=26.2.0=py310h71f11fc_3
  - readline=8.2=h5eee18b_0
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.21.0=py310h505e2c1_0
  - send2trash=1.8.3=pyh0d859eb_0
  - setuptools=75.1.0=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.47.0=h9eae976_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhd8ed1ab_0
  - tornado=6.4.2=py310ha75aee5_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.19.0=py310h1275a96_2
  - zstd=1.5.2=h8a70e8d_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.2.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.9
      - aiosignal==1.3.1
      - array-api-compat==1.12.0
      - async-timeout==5.0.1
      - biom-format==2.1.17
      - biopython==1.84
      - brokenaxes==0.6.2
      - cachetools==5.5.2
      - cairocffi==1.7.1
      - cairosvg==2.8.2
      - certifi==2025.10.5
      - click==8.2.1
      - cloudpickle==3.1.1
      - contourpy==1.3.1
      - cssselect2==0.8.0
      - cycler==0.12.1
      - dask==2025.7.0
      - datasets==3.1.0
      - dill==0.3.8
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - evo-model==0.2.1
      - filelock==3.16.1
      - flash-attn==2.7.0.post2
      - fonttools==4.55.2
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - greenlet==3.2.4
      - grpcio==1.74.0
      - h5py==3.14.0
      - huggingface-hub==0.26.3
      - ipywidgets==8.1.5
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.13
      - keras==3.10.0
      - kiwisolver==1.4.7
      - llvmlite==0.45.1
      - locket==1.0.0
      - lxml==5.4.0
      - mamba-ssm==2.2.4
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - matplotlib==3.9.3
      - matplotlib-venn==1.1.2
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - modlamp==4.3.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mysql-connector-python==9.3.0
      - namex==0.1.0
      - natsort==8.4.0
      - networkx==3.4.2
      - ninja==1.11.1.2
      - nose==1.3.7
      - numba==0.62.1
      - numpy==2.1.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.3.1
      - openpyxl==3.1.5
      - optree==0.17.0
      - outcome==1.3.0.post0
      - pandas==2.2.3
      - partd==1.4.2
      - patsy==1.0.2
      - pillow==11.0.0
      - playwright==1.55.0
      - propcache==0.2.1
      - protobuf==3.20.3
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyee==13.0.0
      - pynndescent==0.5.13
      - pyparsing==3.2.0
      - python-dotenv==1.1.1
      - rdkit==2025.3.3
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rich==14.1.0
      - rsa==4.9.1
      - safetensors==0.4.5
      - scikit-bio==0.7.1.post1
      - scikit-learn==1.7.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - selenium==4.37.0
      - sortedcontainers==2.4.0
      - statsmodels==0.14.6
      - stripedhyena==0.2.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - toolz==1.0.0
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.46.3
      - trio==0.31.0
      - trio-websocket==0.12.2
      - triton==3.1.0
      - typing-extensions==4.15.0
      - tzdata==2024.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - venny4py==1.0.3
      - webdriver-manager==4.0.2
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wsproto==1.2.0
      - xgboost==2.1.3
      - xxhash==3.5.0
      - yarl==1.18.3
